<a href="https://colab.research.google.com/github/Faouzi-Slimi/Tensorflow-Certification/blob/main/Deep_Learning_and_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction To Tensorflow

In [ ]:
# Import tensorfow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# create tensor with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check th dimension of a tensor

scalar.ndim

0

In [ ]:
# create a vector

vector = tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimention of our vector

vector.ndim

1

In [ ]:
# create a matrix

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# check the dimension of our matrix

matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10,7],[7,10]],dtype=tf.float32)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

In [ ]:
# matrix multiplication

mat1 = tf.constant([[1,2,3],[1,2,3],[1,2,3]])
mat2 = mat1*2
mat3 = mat1*4

In [ ]:
# Try to matrix mulltiply tensors of same shape

tf.matmul(mat2,mat3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 48,  96, 144],
       [ 48,  96, 144],
       [ 48,  96, 144]], dtype=int32)>

In [ ]:
# Changing the dtye of tensors

b = tf.constant([1.7,7.4])

b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [ ]:
b =tf.cast(b,dtype=tf.float64)
b

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.70000005, 7.4000001 ])>

In [ ]:
#### Aggregation Tensors



In [ ]:
# Gettting the absulue Value

D = tf.constant([-7,-10])

D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
abs_D = tf.abs(D)
abs_D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Create a random tensor with Values between 0 and 100 of size 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([12,  4, 69, 91, 98, 71,  3, 72, 75, 94, 15, 34, 52, 46, 59, 72, 64,
       81, 59, 73, 43, 27, 73, 57, 60, 10, 38, 54,  2, 70, 78, 30,  7, 36,
       17, 91, 34, 11,  8, 44, 16, 87, 80, 61, 64, 77, 25, 63, 45, 50])>

In [ ]:
# Finding the Minimum 

min = tf.reduce_min(E)
max = tf.reduce_max(E)
mean = tf.reduce_mean(E)

max , min , mean

(<tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50>)

In [ ]:
#### Find the Variance of our tensors

import tensorflow_probability as tfp
tfp.stats.variance(E)

# or
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=760.3984>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.575321>

In [ ]:
#### Find the positional maximum and minimum

# crate new tensors
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])

F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional max

tf.argmax(F)
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
### Squeezing a tensors (removing all single dimensions)
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

G.shape



TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)

G_squeezed.shape

TensorShape([50])

In [ ]:
#### One_hot encoding tensos 


some_list = [0,1,2,3,4]

one_hot_list = tf.one_hot(some_list,depth=4)# we cann add the on_value and the off_value

one_hot_list

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
### Squaring ,log,square root



In [ ]:
# create a tensors
B = tf.range(1,10)

# Find the square 

tf.square(B)
#Find the square root

tf.sqrt(tf.cast(B, dtype = tf.float32))

# find the log

tf.math.log(tf.cast(B,dtype= tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Tensores and Numpy 